unit uDmProdutoCarto;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TdmProdutoCarto = class(TDataModule)
    sdsProdutoCarto: TSQLDataSet;
    cdsProdutoCarto: TClientDataSet;
    dsProdutoCarto: TDataSource;
    sdsProdutoCartoFD: TSQLDataSet;
    cdsProdutoCartoFD: TClientDataSet;
    dsProdutoCartoFD: TDataSource;
    sdsProduto: TSQLDataSet;
    sdsProdutoCODIGO: TIntegerField;
    sdsProdutoCODGRUPO: TIntegerField;
    sdsProdutoCODSUBGRUPO: TIntegerField;
    sdsProdutoREFERENCIA: TStringField;
    sdsProdutoNOME: TStringField;
    sdsProdutoUNIDADE: TStringField;
    sdsProdutoCODCLASFISCAL: TStringField;
    sdsProdutoCODSITTRIB: TIntegerField;
    sdsProdutoLANCAGRADE: TStringField;
    sdsProdutoCODGRADE: TIntegerField;
    sdsProdutoQPARTALAO: TFloatField;
    sdsProdutoPESOLIQUIDO: TFloatField;
    sdsProdutoPESOBRUTO: TFloatField;
    sdsProdutoINATIVO: TStringField;
    sdsProdutoALIQICMS: TFloatField;
    sdsProdutoALIQIPI: TFloatField;
    sdsProdutoNOMEEXP: TStringField;
    sdsProdutoDESCMATERIAL: TStringField;
    sdsProdutoREFERENCIA2: TStringField;
    sdsProdutoVLRATELIER: TFloatField;
    sdsProdutoNOMEMODELO: TStringField;
    sdsProdutoFOTOJPEG: TBlobField;
    sdsProdutoENDETIQ: TStringField;
    sdsProdutoLANCACOR: TStringField;
    sdsProdutoPRECOGRADE: TStringField;
    sdsProdutoVLRVENDA: TFloatField;
    sdsProdutoPRODMAT: TStringField;
    sdsProdutoPRECOCUSTO: TFloatField;
    sdsProdutoPOSSEMAT: TStringField;
    sdsProdutoESTOQUE: TStringField;
    sdsProdutoDTALTERACAO: TDateField;
    sdsProdutoMATERIALOUTROS: TStringField;
    sdsProdutoPRECOCOR: TStringField;
    sdsProdutoCODFORNECEDOR: TIntegerField;
    sdsProdutoESTMINIMO: TFloatField;
    sdsProdutoESTMAXIMO: TFloatField;
    sdsProdutoPERCCOMISSAOVEND: TFloatField;
    sdsProdutoIMPTABPRECO: TStringField;
    sdsProdutoUSUARIO: TStringField;
    sdsProdutoDTCAD: TDateField;
    sdsProdutoHRCAD: TTimeField;
    sdsProdutoCA: TStringField;
    sdsProdutoVINCULARPRODUTO: TStringField;
    sdsProdutoCODPRODUTOEST: TIntegerField;
    sdsProdutoPERCQUEBRATALOES: TFloatField;
    sdsProdutoPERCCOMISSAOVEND2: TFloatField;
    sdsProdutoFICHATECNICACONSPORTAM: TStringField;
    sdsProdutoJUNTARLARGURAEDI: TStringField;
    sdsProdutoIMPMATTALAO: TStringField;
    sdsProdutoCOMPLEMENTO: TStringField;
    sdsProdutoCODTIPOPRODUTO: TIntegerField;
    sdsProdutoCODTIPOMATERIAL: TIntegerField;
    sdsProdutoQTDVOLUME: TIntegerField;
    sdsProdutoCODPROCESSO: TIntegerField;
    sdsProdutoCODCSTIPI: TStringField;
    sdsProdutoTAMCALCULO: TFloatField;
    sdsProdutoORIGEMPROD: TStringField;
    sdsProdutoLOCALCORREDOR: TStringField;
    sdsProdutoLOCALPOSICAO: TStringField;
    sdsProdutoOBS: TMemoField;
    sdsProdutoCODCLIENTE: TIntegerField;
    dspProduto: TDataSetProvider;
    cdsProduto: TClientDataSet;
    cdsProdutoCODIGO: TIntegerField;
    cdsProdutoCODGRUPO: TIntegerField;
    cdsProdutoCODSUBGRUPO: TIntegerField;
    cdsProdutoREFERENCIA: TStringField;
    cdsProdutoNOME: TStringField;
    cdsProdutoUNIDADE: TStringField;
    cdsProdutoCODCLASFISCAL: TStringField;
    cdsProdutoCODSITTRIB: TIntegerField;
    cdsProdutoLANCAGRADE: TStringField;
    cdsProdutoCODGRADE: TIntegerField;
    cdsProdutoQPARTALAO: TFloatField;
    cdsProdutoPESOLIQUIDO: TFloatField;
    cdsProdutoPESOBRUTO: TFloatField;
    cdsProdutoINATIVO: TStringField;
    cdsProdutoALIQICMS: TFloatField;
    cdsProdutoALIQIPI: TFloatField;
    cdsProdutoNOMEEXP: TStringField;
    cdsProdutoDESCMATERIAL: TStringField;
    cdsProdutoREFERENCIA2: TStringField;
    cdsProdutoVLRATELIER: TFloatField;
    cdsProdutoNOMEMODELO: TStringField;
    cdsProdutoFOTOJPEG: TBlobField;
    cdsProdutoENDETIQ: TStringField;
    cdsProdutoLANCACOR: TStringField;
    cdsProdutoPRECOGRADE: TStringField;
    cdsProdutoVLRVENDA: TFloatField;
    cdsProdutoPRODMAT: TStringField;
    cdsProdutoPRECOCUSTO: TFloatField;
    cdsProdutoPOSSEMAT: TStringField;
    cdsProdutoESTOQUE: TStringField;
    cdsProdutoDTALTERACAO: TDateField;
    cdsProdutoMATERIALOUTROS: TStringField;
    cdsProdutoPRECOCOR: TStringField;
    cdsProdutoCODFORNECEDOR: TIntegerField;
    cdsProdutoESTMINIMO: TFloatField;
    cdsProdutoESTMAXIMO: TFloatField;
    cdsProdutoPERCCOMISSAOVEND: TFloatField;
    cdsProdutoIMPTABPRECO: TStringField;
    cdsProdutoUSUARIO: TStringField;
    cdsProdutoDTCAD: TDateField;
    cdsProdutoHRCAD: TTimeField;
    cdsProdutoCA: TStringField;
    cdsProdutoVINCULARPRODUTO: TStringField;
    cdsProdutoCODPRODUTOEST: TIntegerField;
    cdsProdutoPERCQUEBRATALOES: TFloatField;
    cdsProdutoPERCCOMISSAOVEND2: TFloatField;
    cdsProdutoFICHATECNICACONSPORTAM: TStringField;
    cdsProdutoJUNTARLARGURAEDI: TStringField;
    cdsProdutoIMPMATTALAO: TStringField;
    cdsProdutoCOMPLEMENTO: TStringField;
    cdsProdutoCODTIPOPRODUTO: TIntegerField;
    cdsProdutoCODTIPOMATERIAL: TIntegerField;
    cdsProdutoQTDVOLUME: TIntegerField;
    cdsProdutoCODPROCESSO: TIntegerField;
    cdsProdutoCODCSTIPI: TStringField;
    cdsProdutoTAMCALCULO: TFloatField;
    cdsProdutoORIGEMPROD: TStringField;
    cdsProdutoLOCALCORREDOR: TStringField;
    cdsProdutoLOCALPOSICAO: TStringField;
    cdsProdutoOBS: TMemoField;
    cdsProdutoCODCLIENTE: TIntegerField;
    cdsProdutosdsProdutoCarto: TDataSetField;
    cdsProdutosdsProdutoCartoFD: TDataSetField;
    dsProduto: TDataSource;
    dsProdutoMaster: TDataSource;
    sdsProdutoCartoCODIGO: TIntegerField;
    sdsProdutoCartoFD_LARGURA: TFMTBCDField;
    sdsProdutoCartoFD_COMPR: TFMTBCDField;
    sdsProdutoCartoFD_ALTURA: TFMTBCDField;
    sdsProdutoCartoFD_ABA_INT_CAB: TFMTBCDField;
    sdsProdutoCartoFD_ABA_INT_LAT: TFMTBCDField;
    sdsProdutoCartoTP_ABA_EXT_CAB: TFMTBCDField;
    sdsProdutoCartoTP_ABA_INT_CAB: TFMTBCDField;
    sdsProdutoCartoTP_ABA_EXT_LAT: TFMTBCDField;
    sdsProdutoCartoTP_ABA_INT_LAT: TFMTBCDField;
    sdsProdutoCartoSP_LARGURA: TFMTBCDField;
    sdsProdutoCartoSP_COMPR: TFMTBCDField;
    sdsProdutoCartoSP_ALTURA: TFMTBCDField;
    sdsProdutoCartoTP_LARGURA: TFMTBCDField;
    sdsProdutoCartoTP_COMPR: TFMTBCDField;
    sdsProdutoCartoTP_ALTURA: TFMTBCDField;
    sdsProdutoCartoFD_DIMENSAO1: TFMTBCDField;
    sdsProdutoCartoFD_DIMENSAO2: TFMTBCDField;
    sdsProdutoCartoTP_DIMENSAO1: TFMTBCDField;
    sdsProdutoCartoTP_DIMENSAO2: TFMTBCDField;
    sdsProdutoCartoTP_TIPO_MAT: TStringField;
    sdsProdutoCartoSP_ABA_INT_CAB: TFMTBCDField;
    sdsProdutoCartoSP_ABA_INT_LAT: TFMTBCDField;
    sdsProdutoCartoFD_TIPO_MAT: TStringField;
    sdsProdutoCartoSP_TIPO_MAT: TStringField;
    sdsProdutoCartoSP_DIMENSAO1: TFMTBCDField;
    sdsProdutoCartoSP_DIMENSAO2: TFMTBCDField;
    cdsProdutoCartoCODIGO: TIntegerField;
    cdsProdutoCartoFD_LARGURA: TFMTBCDField;
    cdsProdutoCartoFD_COMPR: TFMTBCDField;
    cdsProdutoCartoFD_ALTURA: TFMTBCDField;
    cdsProdutoCartoFD_ABA_INT_CAB: TFMTBCDField;
    cdsProdutoCartoFD_ABA_INT_LAT: TFMTBCDField;
    cdsProdutoCartoTP_ABA_EXT_CAB: TFMTBCDField;
    cdsProdutoCartoTP_ABA_INT_CAB: TFMTBCDField;
    cdsProdutoCartoTP_ABA_EXT_LAT: TFMTBCDField;
    cdsProdutoCartoTP_ABA_INT_LAT: TFMTBCDField;
    cdsProdutoCartoSP_LARGURA: TFMTBCDField;
    cdsProdutoCartoSP_COMPR: TFMTBCDField;
    cdsProdutoCartoSP_ALTURA: TFMTBCDField;
    cdsProdutoCartoTP_LARGURA: TFMTBCDField;
    cdsProdutoCartoTP_COMPR: TFMTBCDField;
    cdsProdutoCartoTP_ALTURA: TFMTBCDField;
    cdsProdutoCartoFD_DIMENSAO1: TFMTBCDField;
    cdsProdutoCartoFD_DIMENSAO2: TFMTBCDField;
    cdsProdutoCartoTP_DIMENSAO1: TFMTBCDField;
    cdsProdutoCartoTP_DIMENSAO2: TFMTBCDField;
    cdsProdutoCartoTP_TIPO_MAT: TStringField;
    cdsProdutoCartoSP_ABA_INT_CAB: TFMTBCDField;
    cdsProdutoCartoSP_ABA_INT_LAT: TFMTBCDField;
    cdsProdutoCartoFD_TIPO_MAT: TStringField;
    cdsProdutoCartoSP_TIPO_MAT: TStringField;
    cdsProdutoCartoSP_DIMENSAO1: TFMTBCDField;
    cdsProdutoCartoSP_DIMENSAO2: TFMTBCDField;
    sdsProdutoCartoFDCODIGO: TIntegerField;
    sdsProdutoCartoFDMATERIAL1: TIntegerField;
    sdsProdutoCartoFDMATERIAL2: TIntegerField;
    sdsProdutoCartoFDMATERIAL3: TIntegerField;
    sdsProdutoCartoFDFECHAMENTO: TStringField;
    sdsProdutoCartoFDFECHAMENTO_CT: TStringField;
    sdsProdutoCartoFDREVEST_FT: TStringField;
    sdsProdutoCartoFDREVEST_FT_MAT: TIntegerField;
    sdsProdutoCartoFDREVEST_FT_BRIL: TStringField;
    sdsProdutoCartoFDREVEST_FT_ATRITO: TStringField;
    sdsProdutoCartoFDREVEST_FT_LUZ: TStringField;
    sdsProdutoCartoFDREVEST_VS: TStringField;
    sdsProdutoCartoFDREVEST_VS_MAT: TIntegerField;
    sdsProdutoCartoFDREVEST_VS_BRIL: TStringField;
    sdsProdutoCartoFDREVEST_VS_ATRITO: TStringField;
    sdsProdutoCartoFDREVEST_VS_LUZ: TStringField;
    sdsProdutoCartoFDAR: TStringField;
    sdsProdutoCartoFDAR_COMPR: TFMTBCDField;
    sdsProdutoCartoFDAR_LARG: TFMTBCDField;
    sdsProdutoCartoFDAR_LOCAL: TStringField;
    sdsProdutoCartoFDBR: TStringField;
    sdsProdutoCartoFDBR_COMPR: TFMTBCDField;
    sdsProdutoCartoFDBR_LARG: TFMTBCDField;
    sdsProdutoCartoFDBR_LOCAL: TStringField;
    sdsProdutoCartoFDHS: TStringField;
    sdsProdutoCartoFDHS_COMPR: TFMTBCDField;
    sdsProdutoCartoFDHS_LARG: TFMTBCDField;
    sdsProdutoCartoFDHS_LOCAL: TStringField;
    sdsProdutoCartoFDVISOR: TStringField;
    sdsProdutoCartoFDVISOR_COMPR: TFMTBCDField;
    sdsProdutoCartoFDVISOR_LARG: TFMTBCDField;
    sdsProdutoCartoFDVISOR_LOCAL: TStringField;
    sdsProdutoCartoFDVERNIZUV: TStringField;
    sdsProdutoCartoFDVERNIZUV_COMPR: TFMTBCDField;
    sdsProdutoCartoFDVERNIZUV_LARG: TFMTBCDField;
    sdsProdutoCartoFDVERNIZUV_LOCAL: TStringField;
    sdsProdutoCartoFDPICOTE: TStringField;
    sdsProdutoCartoFDPICOTE_LOCAL: TStringField;
    sdsProdutoCartoFDPICOTE_TIPO: TStringField;
    sdsProdutoCartoFDPASSAFITA: TStringField;
    sdsProdutoCartoFDPASSAFITA_LOCAL: TStringField;
    sdsProdutoCartoFDPASSAFITA_TIPO: TStringField;
    sdsProdutoCartoFDILHOS: TStringField;
    sdsProdutoCartoFDILHOS_LOCAL: TStringField;
    sdsProdutoCartoFDALCA: TStringField;
    sdsProdutoCartoFDALCA_LOCAL: TStringField;
    sdsProdutoCartoFDVERNIZUV_TOTAL: TStringField;
    cdsProdutoCartoFDCODIGO: TIntegerField;
    cdsProdutoCartoFDMATERIAL1: TIntegerField;
    cdsProdutoCartoFDMATERIAL2: TIntegerField;
    cdsProdutoCartoFDMATERIAL3: TIntegerField;
    cdsProdutoCartoFDFECHAMENTO: TStringField;
    cdsProdutoCartoFDFECHAMENTO_CT: TStringField;
    cdsProdutoCartoFDREVEST_FT: TStringField;
    cdsProdutoCartoFDREVEST_FT_MAT: TIntegerField;
    cdsProdutoCartoFDREVEST_FT_BRIL: TStringField;
    cdsProdutoCartoFDREVEST_FT_ATRITO: TStringField;
    cdsProdutoCartoFDREVEST_FT_LUZ: TStringField;
    cdsProdutoCartoFDREVEST_VS: TStringField;
    cdsProdutoCartoFDREVEST_VS_MAT: TIntegerField;
    cdsProdutoCartoFDREVEST_VS_BRIL: TStringField;
    cdsProdutoCartoFDREVEST_VS_ATRITO: TStringField;
    cdsProdutoCartoFDREVEST_VS_LUZ: TStringField;
    cdsProdutoCartoFDAR: TStringField;
    cdsProdutoCartoFDAR_COMPR: TFMTBCDField;
    cdsProdutoCartoFDAR_LARG: TFMTBCDField;
    cdsProdutoCartoFDAR_LOCAL: TStringField;
    cdsProdutoCartoFDBR: TStringField;
    cdsProdutoCartoFDBR_COMPR: TFMTBCDField;
    cdsProdutoCartoFDBR_LARG: TFMTBCDField;
    cdsProdutoCartoFDBR_LOCAL: TStringField;
    cdsProdutoCartoFDHS: TStringField;
    cdsProdutoCartoFDHS_COMPR: TFMTBCDField;
    cdsProdutoCartoFDHS_LARG: TFMTBCDField;
    cdsProdutoCartoFDHS_LOCAL: TStringField;
    cdsProdutoCartoFDVISOR: TStringField;
    cdsProdutoCartoFDVISOR_COMPR: TFMTBCDField;
    cdsProdutoCartoFDVISOR_LARG: TFMTBCDField;
    cdsProdutoCartoFDVISOR_LOCAL: TStringField;
    cdsProdutoCartoFDVERNIZUV: TStringField;
    cdsProdutoCartoFDVERNIZUV_COMPR: TFMTBCDField;
    cdsProdutoCartoFDVERNIZUV_LARG: TFMTBCDField;
    cdsProdutoCartoFDVERNIZUV_LOCAL: TStringField;
    cdsProdutoCartoFDPICOTE: TStringField;
    cdsProdutoCartoFDPICOTE_LOCAL: TStringField;
    cdsProdutoCartoFDPICOTE_TIPO: TStringField;
    cdsProdutoCartoFDPASSAFITA: TStringField;
    cdsProdutoCartoFDPASSAFITA_LOCAL: TStringField;
    cdsProdutoCartoFDPASSAFITA_TIPO: TStringField;
    cdsProdutoCartoFDILHOS: TStringField;
    cdsProdutoCartoFDILHOS_LOCAL: TStringField;
    cdsProdutoCartoFDALCA: TStringField;
    cdsProdutoCartoFDALCA_LOCAL: TStringField;
    cdsProdutoCartoFDVERNIZUV_TOTAL: TStringField;
    sdsProdutoCartoFDPINCA: TStringField;
    sdsProdutoCartoFDTRAVA: TStringField;
    sdsProdutoCartoFDDISPLAY: TStringField;
    cdsProdutoCartoFDPINCA: TStringField;
    cdsProdutoCartoFDTRAVA: TStringField;
    cdsProdutoCartoFDDISPLAY: TStringField;
    cdsProdutoCartoFDlkMaterial1: TStringField;
    cdsProdutoCartoFDlkMaterial2: TStringField;
    cdsProdutoCartoFDlkMaterial3: TStringField;
    cdsProdutoCartoFDlkRevest_vs: TStringField;
    cdsProdutoCartoFDlkRevest_ft: TStringField;
    sdsProdutoCartoTP: TSQLDataSet;
    cdsProdutoCartoTP: TClientDataSet;
    StringField69: TStringField;
    StringField70: TStringField;
    StringField71: TStringField;
    StringField72: TStringField;
    StringField73: TStringField;
    dsProdutoCartoTP: TDataSource;
    cdsProdutosdsProdutoCartoTP: TDataSetField;
    sdsProdutoCartoTPCODIGO: TIntegerField;
    sdsProdutoCartoTPMATERIAL1: TIntegerField;
    sdsProdutoCartoTPMATERIAL2: TIntegerField;
    sdsProdutoCartoTPMATERIAL3: TIntegerField;
    sdsProdutoCartoTPFECHAMENTO: TStringField;
    sdsProdutoCartoTPREVEST_FT: TStringField;
    sdsProdutoCartoTPREVEST_FT_MAT: TIntegerField;
    sdsProdutoCartoTPREVEST_FT_BRIL: TStringField;
    sdsProdutoCartoTPREVEST_FT_ATRITO: TStringField;
    sdsProdutoCartoTPREVEST_FT_LUZ: TStringField;
    sdsProdutoCartoTPREVEST_VS: TStringField;
    sdsProdutoCartoTPREVEST_VS_MAT: TIntegerField;
    sdsProdutoCartoTPREVEST_VS_BRIL: TStringField;
    sdsProdutoCartoTPREVEST_VS_ATRITO: TStringField;
    sdsProdutoCartoTPREVEST_VS_LUZ: TStringField;
    sdsProdutoCartoTPAR: TStringField;
    sdsProdutoCartoTPAR_COMPR: TFMTBCDField;
    sdsProdutoCartoTPAR_LARG: TFMTBCDField;
    sdsProdutoCartoTPAR_LOCAL: TStringField;
    sdsProdutoCartoTPBR: TStringField;
    sdsProdutoCartoTPBR_COMPR: TFMTBCDField;
    sdsProdutoCartoTPBR_LARG: TFMTBCDField;
    sdsProdutoCartoTPBR_LOCAL: TStringField;
    sdsProdutoCartoTPHS: TStringField;
    sdsProdutoCartoTPHS_COMPR: TFMTBCDField;
    sdsProdutoCartoTPHS_LARG: TFMTBCDField;
    sdsProdutoCartoTPHS_LOCAL: TStringField;
    sdsProdutoCartoTPVISOR: TStringField;
    sdsProdutoCartoTPVISOR_COMPR: TFMTBCDField;
    sdsProdutoCartoTPVISOR_LARG: TFMTBCDField;
    sdsProdutoCartoTPVISOR_LOCAL: TStringField;
    sdsProdutoCartoTPVERNIZUV: TStringField;
    sdsProdutoCartoTPVERNIZUV_COMPR: TFMTBCDField;
    sdsProdutoCartoTPVERNIZUV_LARG: TFMTBCDField;
    sdsProdutoCartoTPVERNIZUV_LOCAL: TStringField;
    sdsProdutoCartoTPPICOTE: TStringField;
    sdsProdutoCartoTPPICOTE_LOCAL: TStringField;
    sdsProdutoCartoTPPICOTE_TIPO: TStringField;
    sdsProdutoCartoTPPASSAFITA: TStringField;
    sdsProdutoCartoTPPASSAFITA_LOCAL: TStringField;
    sdsProdutoCartoTPPASSAFITA_TIPO: TStringField;
    sdsProdutoCartoTPILHOS: TStringField;
    sdsProdutoCartoTPILHOS_LOCAL: TStringField;
    sdsProdutoCartoTPALCA: TStringField;
    sdsProdutoCartoTPALCA_LOCAL: TStringField;
    sdsProdutoCartoTPVERNIZUV_TOTAL: TStringField;
    sdsProdutoCartoTPPINCA: TStringField;
    cdsProdutoCartoTPCODIGO: TIntegerField;
    cdsProdutoCartoTPMATERIAL1: TIntegerField;
    cdsProdutoCartoTPMATERIAL2: TIntegerField;
    cdsProdutoCartoTPMATERIAL3: TIntegerField;
    cdsProdutoCartoTPFECHAMENTO: TStringField;
    cdsProdutoCartoTPREVEST_FT: TStringField;
    cdsProdutoCartoTPREVEST_FT_MAT: TIntegerField;
    cdsProdutoCartoTPREVEST_FT_BRIL: TStringField;
    cdsProdutoCartoTPREVEST_FT_ATRITO: TStringField;
    cdsProdutoCartoTPREVEST_FT_LUZ: TStringField;
    cdsProdutoCartoTPREVEST_VS: TStringField;
    cdsProdutoCartoTPREVEST_VS_MAT: TIntegerField;
    cdsProdutoCartoTPREVEST_VS_BRIL: TStringField;
    cdsProdutoCartoTPREVEST_VS_ATRITO: TStringField;
    cdsProdutoCartoTPREVEST_VS_LUZ: TStringField;
    cdsProdutoCartoTPAR: TStringField;
    cdsProdutoCartoTPAR_COMPR: TFMTBCDField;
    cdsProdutoCartoTPAR_LARG: TFMTBCDField;
    cdsProdutoCartoTPAR_LOCAL: TStringField;
    cdsProdutoCartoTPBR: TStringField;
    cdsProdutoCartoTPBR_COMPR: TFMTBCDField;
    cdsProdutoCartoTPBR_LARG: TFMTBCDField;
    cdsProdutoCartoTPBR_LOCAL: TStringField;
    cdsProdutoCartoTPHS: TStringField;
    cdsProdutoCartoTPHS_COMPR: TFMTBCDField;
    cdsProdutoCartoTPHS_LARG: TFMTBCDField;
    cdsProdutoCartoTPHS_LOCAL: TStringField;
    cdsProdutoCartoTPVISOR: TStringField;
    cdsProdutoCartoTPVISOR_COMPR: TFMTBCDField;
    cdsProdutoCartoTPVISOR_LARG: TFMTBCDField;
    cdsProdutoCartoTPVISOR_LOCAL: TStringField;
    cdsProdutoCartoTPVERNIZUV: TStringField;
    cdsProdutoCartoTPVERNIZUV_COMPR: TFMTBCDField;
    cdsProdutoCartoTPVERNIZUV_LARG: TFMTBCDField;
    cdsProdutoCartoTPVERNIZUV_LOCAL: TStringField;
    cdsProdutoCartoTPPICOTE: TStringField;
    cdsProdutoCartoTPPICOTE_LOCAL: TStringField;
    cdsProdutoCartoTPPICOTE_TIPO: TStringField;
    cdsProdutoCartoTPPASSAFITA: TStringField;
    cdsProdutoCartoTPPASSAFITA_LOCAL: TStringField;
    cdsProdutoCartoTPPASSAFITA_TIPO: TStringField;
    cdsProdutoCartoTPILHOS: TStringField;
    cdsProdutoCartoTPILHOS_LOCAL: TStringField;
    cdsProdutoCartoTPALCA: TStringField;
    cdsProdutoCartoTPALCA_LOCAL: TStringField;
    cdsProdutoCartoTPVERNIZUV_TOTAL: TStringField;
    cdsProdutoCartoTPPINCA: TStringField;
    sdsProdutoCartoSP: TSQLDataSet;
    cdsProdutoCartoSP: TClientDataSet;
    dsProdutoCartoSP: TDataSource;
    sdsProdutoCartoSPCODIGO: TIntegerField;
    sdsProdutoCartoSPMATERIAL1: TIntegerField;
    sdsProdutoCartoSPMATERIAL2: TIntegerField;
    sdsProdutoCartoSPMATERIAL3: TIntegerField;
    sdsProdutoCartoSPFECHAMENTO: TStringField;
    sdsProdutoCartoSPREVEST_FT: TStringField;
    sdsProdutoCartoSPREVEST_FT_MAT: TIntegerField;
    sdsProdutoCartoSPREVEST_FT_BRIL: TStringField;
    sdsProdutoCartoSPREVEST_FT_ATRITO: TStringField;
    sdsProdutoCartoSPREVEST_FT_LUZ: TStringField;
    sdsProdutoCartoSPREVEST_VS: TStringField;
    sdsProdutoCartoSPREVEST_VS_MAT: TIntegerField;
    sdsProdutoCartoSPREVEST_VS_BRIL: TStringField;
    sdsProdutoCartoSPREVEST_VS_ATRITO: TStringField;
    sdsProdutoCartoSPREVEST_VS_LUZ: TStringField;
    sdsProdutoCartoSPAR: TStringField;
    sdsProdutoCartoSPAR_COMPR: TFMTBCDField;
    sdsProdutoCartoSPAR_LARG: TFMTBCDField;
    sdsProdutoCartoSPAR_LOCAL: TStringField;
    sdsProdutoCartoSPBR: TStringField;
    sdsProdutoCartoSPBR_COMPR: TFMTBCDField;
    sdsProdutoCartoSPBR_LARG: TFMTBCDField;
    sdsProdutoCartoSPBR_LOCAL: TStringField;
    sdsProdutoCartoSPHS: TStringField;
    sdsProdutoCartoSPHS_COMPR: TFMTBCDField;
    sdsProdutoCartoSPHS_LARG: TFMTBCDField;
    sdsProdutoCartoSPHS_LOCAL: TStringField;
    sdsProdutoCartoSPVISOR: TStringField;
    sdsProdutoCartoSPVISOR_COMPR: TFMTBCDField;
    sdsProdutoCartoSPVISOR_LARG: TFMTBCDField;
    sdsProdutoCartoSPVISOR_LOCAL: TStringField;
    sdsProdutoCartoSPVERNIZUV: TStringField;
    sdsProdutoCartoSPVERNIZUV_COMPR: TFMTBCDField;
    sdsProdutoCartoSPVERNIZUV_LARG: TFMTBCDField;
    sdsProdutoCartoSPVERNIZUV_LOCAL: TStringField;
    sdsProdutoCartoSPPICOTE: TStringField;
    sdsProdutoCartoSPPICOTE_LOCAL: TStringField;
    sdsProdutoCartoSPPICOTE_TIPO: TStringField;
    sdsProdutoCartoSPPASSAFITA: TStringField;
    sdsProdutoCartoSPPASSAFITA_LOCAL: TStringField;
    sdsProdutoCartoSPPASSAFITA_TIPO: TStringField;
    sdsProdutoCartoSPILHOS: TStringField;
    sdsProdutoCartoSPILHOS_LOCAL: TStringField;
    sdsProdutoCartoSPALCA: TStringField;
    sdsProdutoCartoSPALCA_LOCAL: TStringField;
    sdsProdutoCartoSPVERNIZUV_TOTAL: TStringField;
    sdsProdutoCartoSPPINCA: TStringField;
    cdsProdutoCartoSPCODIGO: TIntegerField;
    cdsProdutoCartoSPMATERIAL1: TIntegerField;
    cdsProdutoCartoSPMATERIAL2: TIntegerField;
    cdsProdutoCartoSPMATERIAL3: TIntegerField;
    cdsProdutoCartoSPFECHAMENTO: TStringField;
    cdsProdutoCartoSPREVEST_FT: TStringField;
    cdsProdutoCartoSPREVEST_FT_MAT: TIntegerField;
    cdsProdutoCartoSPREVEST_FT_BRIL: TStringField;
    cdsProdutoCartoSPREVEST_FT_ATRITO: TStringField;
    cdsProdutoCartoSPREVEST_FT_LUZ: TStringField;
    cdsProdutoCartoSPREVEST_VS: TStringField;
    cdsProdutoCartoSPREVEST_VS_MAT: TIntegerField;
    cdsProdutoCartoSPREVEST_VS_BRIL: TStringField;
    cdsProdutoCartoSPREVEST_VS_ATRITO: TStringField;
    cdsProdutoCartoSPREVEST_VS_LUZ: TStringField;
    cdsProdutoCartoSPAR: TStringField;
    cdsProdutoCartoSPAR_COMPR: TFMTBCDField;
    cdsProdutoCartoSPAR_LARG: TFMTBCDField;
    cdsProdutoCartoSPAR_LOCAL: TStringField;
    cdsProdutoCartoSPBR: TStringField;
    cdsProdutoCartoSPBR_COMPR: TFMTBCDField;
    cdsProdutoCartoSPBR_LARG: TFMTBCDField;
    cdsProdutoCartoSPBR_LOCAL: TStringField;
    cdsProdutoCartoSPHS: TStringField;
    cdsProdutoCartoSPHS_COMPR: TFMTBCDField;
    cdsProdutoCartoSPHS_LARG: TFMTBCDField;
    cdsProdutoCartoSPHS_LOCAL: TStringField;
    cdsProdutoCartoSPVISOR: TStringField;
    cdsProdutoCartoSPVISOR_COMPR: TFMTBCDField;
    cdsProdutoCartoSPVISOR_LARG: TFMTBCDField;
    cdsProdutoCartoSPVISOR_LOCAL: TStringField;
    cdsProdutoCartoSPVERNIZUV: TStringField;
    cdsProdutoCartoSPVERNIZUV_COMPR: TFMTBCDField;
    cdsProdutoCartoSPVERNIZUV_LARG: TFMTBCDField;
    cdsProdutoCartoSPVERNIZUV_LOCAL: TStringField;
    cdsProdutoCartoSPPICOTE: TStringField;
    cdsProdutoCartoSPPICOTE_LOCAL: TStringField;
    cdsProdutoCartoSPPICOTE_TIPO: TStringField;
    cdsProdutoCartoSPPASSAFITA: TStringField;
    cdsProdutoCartoSPPASSAFITA_LOCAL: TStringField;
    cdsProdutoCartoSPPASSAFITA_TIPO: TStringField;
    cdsProdutoCartoSPILHOS: TStringField;
    cdsProdutoCartoSPILHOS_LOCAL: TStringField;
    cdsProdutoCartoSPALCA: TStringField;
    cdsProdutoCartoSPALCA_LOCAL: TStringField;
    cdsProdutoCartoSPVERNIZUV_TOTAL: TStringField;
    cdsProdutoCartoSPPINCA: TStringField;
    cdsProdutosdsProdutoCartoSP: TDataSetField;
    cdsProdutoCartoSPlkMaterial1: TStringField;
    cdsProdutoCartoSPlkMaterial2: TStringField;
    cdsProdutoCartoSPlkMaterial3: TStringField;
    cdsProdutoCartoSPlkRevest_vs: TStringField;
    cdsProdutoCartoSPlkRevest_ft: TStringField;
    sdsProdutoCartoFDPINCA_TAM: TFMTBCDField;
    sdsProdutoCartoTPPINCA_TAM: TFMTBCDField;
    sdsProdutoCartoSPPINCA_TAM: TFMTBCDField;
    cdsProdutoCartoFDPINCA_TAM: TFMTBCDField;
    cdsProdutoCartoTPPINCA_TAM: TFMTBCDField;
    cdsProdutoCartoSPPINCA_TAM: TFMTBCDField;
    sdsProdutoCartoTIPO: TStringField;
    cdsProdutoCartoTIPO: TStringField;
    sdsProdutoCartoFDGRUPO1: TIntegerField;
    sdsProdutoCartoFDSUBGRUPO1: TIntegerField;
    sdsProdutoCartoFDGRUPO2: TIntegerField;
    sdsProdutoCartoFDSUBGRUPO2: TIntegerField;
    sdsProdutoCartoFDGRUPO3: TIntegerField;
    sdsProdutoCartoFDSUBGRUPO3: TIntegerField;
    sdsProdutoCartoTPGRUPO1: TIntegerField;
    sdsProdutoCartoTPSUBGRUPO1: TIntegerField;
    sdsProdutoCartoTPGRUPO2: TIntegerField;
    sdsProdutoCartoTPSUBGRUPO2: TIntegerField;
    sdsProdutoCartoTPGRUPO3: TIntegerField;
    sdsProdutoCartoTPSUBGRUPO3: TIntegerField;
    sdsProdutoCartoSPGRUPO1: TIntegerField;
    sdsProdutoCartoSPSUBGRUPO1: TIntegerField;
    sdsProdutoCartoSPGRUPO2: TIntegerField;
    sdsProdutoCartoSPSUBGRUPO2: TIntegerField;
    sdsProdutoCartoSPGRUPO3: TIntegerField;
    sdsProdutoCartoSPSUBGRUPO3: TIntegerField;
    cdsProdutoCartoFDGRUPO1: TIntegerField;
    cdsProdutoCartoFDSUBGRUPO1: TIntegerField;
    cdsProdutoCartoFDGRUPO2: TIntegerField;
    cdsProdutoCartoFDSUBGRUPO2: TIntegerField;
    cdsProdutoCartoFDGRUPO3: TIntegerField;
    cdsProdutoCartoFDSUBGRUPO3: TIntegerField;
    cdsProdutoCartoTPGRUPO1: TIntegerField;
    cdsProdutoCartoTPSUBGRUPO1: TIntegerField;
    cdsProdutoCartoTPGRUPO2: TIntegerField;
    cdsProdutoCartoTPSUBGRUPO2: TIntegerField;
    cdsProdutoCartoTPGRUPO3: TIntegerField;
    cdsProdutoCartoTPSUBGRUPO3: TIntegerField;
    cdsProdutoCartoSPGRUPO1: TIntegerField;
    cdsProdutoCartoSPSUBGRUPO1: TIntegerField;
    cdsProdutoCartoSPGRUPO2: TIntegerField;
    cdsProdutoCartoSPSUBGRUPO2: TIntegerField;
    cdsProdutoCartoSPGRUPO3: TIntegerField;
    cdsProdutoCartoSPSUBGRUPO3: TIntegerField;
    cdsProdutoCartoclTipo: TStringField;
    sdsProdutoCartoFACA_FD: TIntegerField;
    sdsProdutoCartoFACA_TP: TIntegerField;
    sdsProdutoCartoFACA_SP: TIntegerField;
    cdsProdutoCartoFACA_FD: TIntegerField;
    cdsProdutoCartoFACA_TP: TIntegerField;
    cdsProdutoCartoFACA_SP: TIntegerField;
    sdsProdutoCartoENDERECO: TStringField;
    sdsProdutoCartoFACA_ID: TIntegerField;
    sdsProdutoCartoOBS: TMemoField;
    cdsProdutoCartoENDERECO: TStringField;
    cdsProdutoCartoFACA_ID: TIntegerField;
    cdsProdutoCartoOBS: TMemoField;
    sdsProdutoCartoFD_INT_L: TFMTBCDField;
    sdsProdutoCartoFD_INT_C: TFMTBCDField;
    sdsProdutoCartoTP_INT_L: TFMTBCDField;
    sdsProdutoCartoTP_INT_C: TFMTBCDField;
    sdsProdutoCartoSP_INT_L: TFMTBCDField;
    sdsProdutoCartoSP_INT_C: TFMTBCDField;
    cdsProdutoCartoFD_INT_L: TFMTBCDField;
    cdsProdutoCartoFD_INT_C: TFMTBCDField;
    cdsProdutoCartoTP_INT_L: TFMTBCDField;
    cdsProdutoCartoTP_INT_C: TFMTBCDField;
    cdsProdutoCartoSP_INT_L: TFMTBCDField;
    cdsProdutoCartoSP_INT_C: TFMTBCDField;
    sdsProdutoCartoFD_COPIAS_C: TSmallintField;
    sdsProdutoCartoTP_COPIAS_C: TSmallintField;
    sdsProdutoCartoSP_COPIAS_C: TSmallintField;
    sdsProdutoCartoFD_COPIAS_L: TSmallintField;
    sdsProdutoCartoTP_COPIAS_L: TSmallintField;
    sdsProdutoCartoSP_COPIAS_L: TSmallintField;
    cdsProdutoCartoFD_COPIAS_C: TSmallintField;
    cdsProdutoCartoTP_COPIAS_C: TSmallintField;
    cdsProdutoCartoSP_COPIAS_C: TSmallintField;
    cdsProdutoCartoFD_COPIAS_L: TSmallintField;
    cdsProdutoCartoTP_COPIAS_L: TSmallintField;
    cdsProdutoCartoSP_COPIAS_L: TSmallintField;
    sdsProdutoCartoFACA: TStringField;
    sdsProdutoCartoFD_FIO_C: TFMTBCDField;
    sdsProdutoCartoFD_FIO_L: TFMTBCDField;
    sdsProdutoCartoTP_FIO_C: TFMTBCDField;
    sdsProdutoCartoTP_FIO_L: TFMTBCDField;
    sdsProdutoCartoSP_FIO_C: TFMTBCDField;
    sdsProdutoCartoSP_FIO_L: TFMTBCDField;
    cdsProdutoCartoFACA: TStringField;
    cdsProdutoCartoFD_FIO_C: TFMTBCDField;
    cdsProdutoCartoFD_FIO_L: TFMTBCDField;
    cdsProdutoCartoTP_FIO_C: TFMTBCDField;
    cdsProdutoCartoTP_FIO_L: TFMTBCDField;
    cdsProdutoCartoSP_FIO_C: TFMTBCDField;
    cdsProdutoCartoSP_FIO_L: TFMTBCDField;
    sdsProdutoCartoFDOBS: TStringField;
    sdsProdutoCartoTPOBS: TStringField;
    sdsProdutoCartoSPOBS: TStringField;
    cdsProdutoCartoFDOBS: TStringField;
    cdsProdutoCartoTPOBS: TStringField;
    cdsProdutoCartoSPOBS: TStringField;
    procedure cdsProdutoCartoFDNewRecord(DataSet: TDataSet);
    procedure cdsProdutoCartoCalcFields(DataSet: TDataSet);
    procedure dspProdutoUpdateError(Sender: TObject;
      DataSet: TCustomClientDataSet; E: EUpdateError;
      UpdateKind: TUpdateKind; var Response: TResolverResponse);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmProdutoCarto: TdmProdutoCarto;

implementation

uses DmdDatabase, dmdCadProduto, uDm1;

{$R *.dfm}

procedure TdmProdutoCarto.cdsProdutoCartoFDNewRecord(DataSet: TDataSet);
begin
  cdsProdutoCartoFDPINCA.AsString         := 'S';
  cdsProdutoCartoFDPINCA_TAM.AsFloat      := 1.2;
  cdsProdutoCartoFDTrava.AsString         := 'N';
  cdsProdutoCartoFDDISPLAY.AsString       := 'N';
  cdsProdutoCartoFDFECHAMENTO_CT.AsString := '0';
  cdsProdutoCartoFDALCA.AsString          := '0';
  cdsProdutoCartoFDAR.AsString            := '0';
  cdsProdutoCartoFDBR.AsString            := '0';
  cdsProdutoCartoFDHS.AsString            := '0';
  cdsProdutoCartoFDILHOS.AsString         := '0';
  cdsProdutoCartoFDPASSAFITA.AsString     := '0';
  cdsProdutoCartoFDPICOTE.AsString        := '0';
  cdsProdutoCartoFDREVEST_FT.AsString     := '0';
  cdsProdutoCartoFDREVEST_VS.AsString     := '0';
  cdsProdutoCartoFDTRAVA.AsString         := '0';
  cdsProdutoCartoFDVERNIZUV.AsString      := '0';
  cdsProdutoCartoFDVERNIZUV_TOTAL.AsString := '0';
  cdsProdutoCartoFDVISOR.AsString         := '0';
end;

procedure TdmProdutoCarto.cdsProdutoCartoCalcFields(DataSet: TDataSet);
begin
  if not cdsProdutoCartoTIPO.IsNull then
    case cdsProdutoCartoTIPO.AsInteger of
      1: cdsProdutoCartoclTIPO.AsString := 'CAIXA NORMAL';
      2: cdsProdutoCartoclTIPO.AsString := 'TAMPA ACOPLADA';
      3: cdsProdutoCartoclTIPO.AsString := 'CARTUCHO';
      4: cdsProdutoCartoclTIPO.AsString := 'SACOLA';
      5: cdsProdutoCartoclTIPO.AsString := 'FACA';
    end;
end;

procedure TdmProdutoCarto.dspProdutoUpdateError(Sender: TObject;
  DataSet: TCustomClientDataSet; E: EUpdateError; UpdateKind: TUpdateKind;
  var Response: TResolverResponse);
begin
  Response := rrAbort;
  raise exception.Create(E.Message);
end;

end.
